# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OtpMigration.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12OtpMigration.proto\"\xc9\x01\n\x10MigrationPayload\x12\x30\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x0e.OtpParameters\x12\x10\n\x07version\x18\x02 \x01(\x05\x12\x12\n\tbatch_size\x18\x03 \x01(\x05\x12\x14\n\x0bbatch_index\x18\x04 \x01(\x05\x12\x10\n\x07batch_id\x18\x05 \x01(\x05\"\\\n\x0eOtpParameters\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06\x63ounter\x18\x05 \x01(\x03\x12\x12\n\nalgorithm\x18\x06 \x01(\x05\x12\x0e\n\x06\x64igits\x18\x07 \x01(\x05\x12\x0e\n\x06period\x18\x08 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OtpMigration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _MIGRATIONPAYLOAD._serialized_start=22
  _MIGRATIONPAYLOAD._serialized_end=213
  _OTPPARAMETERS._serialized_start=215
  _OTPPARAMETERS._serialized_end=301
# @@protoc_insertion_point(module_scope)